# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-08-22 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementoModeloAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modelo', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=800)),
                ('tipo', models.IntegerField(choices=[(1, 'Resposta Exclusiva'), (2, 'Resposta M\xfaltipla'), (3, 'Resposta Recorrente')], default=1)),
                ('limite', models.IntegerField(blank=True, null=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.ProdutoAuto')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaModeloAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=800)),
                ('tipo', models.IntegerField(choices=[(1, 'Resposta Exclusiva'), (2, 'Resposta M\xfaltipla'), (3, 'Resposta Recorrente')], default=1)),
                ('limite', models.IntegerField(blank=True, null=True)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.ComplementoModeloAuto')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=400)),
                ('sem_acento', models.CharField(blank=True, max_length=400, null=True)),
                ('preco_adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.PerguntaAuto')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=400)),
                ('preco_adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.PerguntaModeloAuto')),
            ],
        ),
    ]
