# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-08-22 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0002_complementomodeloauto_perguntaauto_perguntamodeloauto_respostaauto_respostamodelo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RespostaModelo',
            new_name='RespostaModeloAuto',
        ),
    ]
