# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-08-23 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0004_codigo_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='numero_mesa',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
