# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-08-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0005_mesa_numero_mesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Comanda Aberta'), (2, 'Comanda Fechada')], default=1)),
                ('hora_abertura', models.DateTimeField(blank=True, null=True)),
                ('hora_fechamento', models.DateTimeField(blank=True, null=True)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.Mesa')),
            ],
        ),
        migrations.CreateModel(
            name='ComandaSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=50)),
                ('comanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.Comanda')),
            ],
        ),
        migrations.CreateModel(
            name='CompradorPedidoAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=400)),
                ('sobrenome', models.CharField(blank=True, max_length=400, null=True)),
                ('telefone', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_itens', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('pedido_especial', models.TextField(blank=True, null=True)),
                ('hora_criacao', models.DateTimeField(blank=True, null=True)),
                ('hora_atendimento', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pedido no Carrinho'), (2, 'Novo Pedido'), (3, 'Em Andamento'), (4, 'Pedido Finalizado')], default=1)),
                ('comanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.Comanda')),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.CompradorPedidoAuto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoPedidoAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complemento', models.TextField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('preco_produto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.ProdutoAuto')),
            ],
        ),
        migrations.AddField(
            model_name='pedidoauto',
            name='produtos',
            field=models.ManyToManyField(blank=True, to='onshop_auto.ProdutoPedidoAuto'),
        ),
    ]
