# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-08-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0007_comanda_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoauto',
            name='session_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
