# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-09-10 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0008_pedidoauto_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaauto',
            name='tempo_preparo',
            field=models.CharField(default='10 minutos', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoauto',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pedido no Carrinho'), (2, 'Novo Pedido'), (3, 'Em Andamento'), (4, 'Pedido Entregue')], default=1),
        ),
    ]
