# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-09-13 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0009_auto_20190910_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('comanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.Comanda')),
            ],
        ),
    ]
