# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-10-22 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0011_auto_20190913_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedidoAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_criacao', models.DateTimeField(blank=True, null=True)),
                ('hora_atendimento', models.DateTimeField(blank=True, null=True)),
                ('complemento', models.TextField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('preco_produto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('comanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.Comanda')),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.CompradorPedidoAuto')),
                ('pedido_atrelado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.PedidoAuto')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.ProdutoAuto')),
            ],
        ),
    ]
