# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-19 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0014_auto_20191203_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradorpedidoauto',
            name='email',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='compradorpedidoauto',
            name='nome',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
