# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-22 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0015_auto_20200119_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='endereco',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
