# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-22 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0016_codigo_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='scheme',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
