# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-30 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0018_auto_20200123_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_primeiro_campo', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('nota_segundo_campo', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('nota_terceiro_campo', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('nota_quarto_campo', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('hora_criacao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QAvaliado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_primeiro_campo', models.CharField(default='Tempo', max_length=50)),
                ('nome_segundo_campo', models.CharField(default='Limpeza', max_length=50)),
                ('nome_terceiro_campo', models.CharField(default='Atendimento', max_length=50)),
                ('nome_quarto_campo', models.CharField(default='Produtos', max_length=50)),
            ],
        ),
    ]
