# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-02-06 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0019_avaliacao_qavaliado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garcom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=20)),
                ('hora_criacao', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde_dias', models.IntegerField(blank=True, null=True)),
                ('nota_primeiro_campo', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('nota_segundo_campo', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('nota_terceiro_campo', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('nota_quarto_campo', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('hora_calculada', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pedidoauto',
            name='garcom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_auto.Garcom'),
        ),
    ]
