# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-02-14 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0020_auto_20200206_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoauto',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pedido no Carrinho'), (2, 'Novo Pedido'), (3, 'Em Andamento'), (4, 'Pedido Entregue'), (5, 'Pedido Rejeitado')], default=1),
        ),
    ]
