# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-02-14 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0021_auto_20200213_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='garcom',
            name='token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
