# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-25 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('icone', models.ImageField(null=True, upload_to='uploads/icones/', verbose_name='Atributo')),
            ],
        ),
        migrations.CreateModel(
            name='BairrosAtendidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplementoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modelo', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='CompradorPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400)),
                ('sobrenome', models.CharField(blank=True, max_length=400, null=True)),
                ('telefone', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(blank=True, max_length=25, null=True)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_abertura', models.TimeField(blank=True, null=True)),
                ('horario_fechamento', models.TimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Aberto'), (2, 'Fechado')], default=2)),
                ('tempo_espera', models.CharField(blank=True, default='50 minutos', max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalRetiradaPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=400)),
                ('numero', models.CharField(blank=True, max_length=255, null=True)),
                ('ed_apto_bloco', models.CharField(blank=True, max_length=400, null=True)),
                ('pto_referencia', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpcaoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(blank=True, max_length=400, null=True)),
                ('troco', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=50)),
                ('quantidade_itens', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('pedido_especial', models.TextField(blank=True, null=True)),
                ('hora_criacao', models.DateTimeField(blank=True, null=True)),
                ('hora_atendimento', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pedido no Carrinho'), (2, 'Novo Pedido'), (3, 'Em Andamento'), (4, 'Pedido Finalizado')], default=1)),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_core.CompradorPedido')),
                ('opcao_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_core.OpcaoPagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=800)),
                ('tipo', models.IntegerField(choices=[(1, 'Resposta Exclusiva'), (2, 'Resposta M\xfaltipla'), (3, 'Resposta Recorrente')], default=1)),
                ('limite', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=800)),
                ('tipo', models.IntegerField(choices=[(1, 'Resposta Exclusiva'), (2, 'Resposta M\xfaltipla'), (3, 'Resposta Recorrente')], default=1)),
                ('limite', models.IntegerField(blank=True, null=True)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_core.ComplementoModelo')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='uploads/produtos/', verbose_name='ImagemProduto')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/produtos/', verbose_name='ThumbnailProduto')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('preco_promocao', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pedido_especial', models.TextField(blank=True, null=True)),
                ('esgotado', models.IntegerField(choices=[(0, 'Nao'), (1, 'Sim')], default=0)),
                ('atributos', models.ManyToManyField(blank=True, to='onshop_core.Atributo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onshop_core.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complemento', models.TextField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('preco_produto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_core.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='PushSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, max_length=200, null=True)),
                ('authorization', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateTimeField()),
                ('quantidade_pedidos', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=400)),
                ('sem_acento', models.CharField(blank=True, max_length=400, null=True)),
                ('preco_adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_core.Pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=400)),
                ('preco_adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_core.PerguntaModelo')),
            ],
        ),
        migrations.AddField(
            model_name='pergunta',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_core.Produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(blank=True, to='onshop_core.ProdutoPedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='retirada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_core.LocalRetiradaPedido'),
        ),
        migrations.AddField(
            model_name='bairrosatendidos',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onshop_core.Estabelecimento'),
        ),
    ]
