# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-23 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_core', '0005_auto_20191203_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='pedido_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
