# Generated by Django 3.0.3 on 2020-02-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_core', '0006_auto_20200123_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_restaurante', models.IntegerField(verbose_name='Id do Restaurante')),
                ('id_mesa', models.IntegerField(verbose_name='Número da Mesa')),
            ],
        ),
        migrations.CreateModel(
            name='PProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_restaurante', models.IntegerField(verbose_name='Id do Restaurante')),
                ('id_prod', models.IntegerField(verbose_name='Número da Mesa')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
