# Generated by Django 3.0.3 on 2020-02-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_core', '0007_pmesa_pproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFormasPag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_forma', models.IntegerField(verbose_name='Id da forma de pagamento')),
                ('id_restaurante', models.IntegerField(verbose_name='Id do Restaurante')),
                ('forma', models.CharField(max_length=200, verbose_name='Forma de pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='PPedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.IntegerField(verbose_name='Id do Restaurante')),
                ('id_restaurante', models.IntegerField(verbose_name='Id do Restaurante')),
                ('id_mesa', models.IntegerField(verbose_name='Número da Mesa')),
                ('id_produto', models.IntegerField(verbose_name='Id do Produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='PPedidosFormaPag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.IntegerField(verbose_name='Id do Restaurante')),
                ('id_forma', models.IntegerField(verbose_name='Id da forma de pagamento')),
                ('id_restaurante', models.IntegerField(verbose_name='Id do Restaurante')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('forma', models.CharField(max_length=200, verbose_name='Forma de pagamento')),
            ],
        ),
        migrations.AlterField(
            model_name='pproduto',
            name='id_prod',
            field=models.IntegerField(verbose_name='Id do Produto'),
        ),
    ]
