# Generated by Django 3.0.3 on 2020-02-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_core', '0008_auto_20200220_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppedidosformapag',
            name='id_forma',
        ),
        migrations.RemoveField(
            model_name='ppedidosformapag',
            name='id_restaurante',
        ),
        migrations.AlterField(
            model_name='pmesa',
            name='id_mesa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pmesa',
            name='id_restaurante',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ppedidosformapag',
            name='id_pedido',
            field=models.IntegerField(verbose_name='Id do Pedido'),
        ),
    ]
