# Generated by Django 3.0.3 on 2020-02-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_core', '0009_auto_20200220_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppedidosformapag',
            name='mesa',
            field=models.IntegerField(default=0, verbose_name='Mesa'),
        ),
    ]
