# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-05-22 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleNovaSenha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
